version: '3'
services:

  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # salva persistentemente il db nel volume indicato
  www:
    #image: php:apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html" # sincronizza la cartella del progetto nel percorso indicato all'interno del container
    ports:
      - 80:80
      - 443:443
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

